$primary_paletteKeyColor = f106ff
$secondary_paletteKeyColor = 936b83
$tertiary_paletteKeyColor = a2657c
$neutral_paletteKeyColor = 81737e
$neutral_variant_paletteKeyColor = 83727f
$background = 080308
$onBackground = efddea
$surface = 080308
$surfaceDim = 080308
$surfaceBright = 140f13
$surfaceContainerLowest = 060206
$surfaceContainerLow = 0b060b
$surfaceContainer = 0d070c
$surfaceContainerHigh = 100a10
$surfaceContainerHighest = 130d13
$onSurface = efddea
$surfaceVariant = 181117
$onSurfaceVariant = d5c1cf
$inverseSurface = efddea
$inverseOnSurface = 382d36
$outline = 9d8c99
$outlineVariant = 51424e
$shadow = 000000
$scrim = 000000
$surfaceTint = 421444
$primary = ffa9fa
$onPrimary = 5a005f
$primaryContainer = 7f0087
$onPrimaryContainer = ffd6f8
$inversePrimary = a600b0
$secondary = e8b9d4
$onSecondary = 46263b
$secondaryContainer = 5f3c52
$onSecondaryContainer = ffd8ed
$tertiary = fbb2cb
$onTertiary = 502034
$tertiaryContainer = bf7e95
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd6f8
$primaryFixedDim = ffa9fa
$onPrimaryFixed = 37003b
$onPrimaryFixedVariant = 7f0087
$secondaryFixed = ffd8ed
$secondaryFixedDim = e8b9d4
$onSecondaryFixed = 2e1125
$onSecondaryFixedVariant = 5f3c52
$tertiaryFixed = ffd9e4
$tertiaryFixedDim = fbb2cb
$onTertiaryFixed = 360b1f
$onTertiaryFixedVariant = 6b364b
$term0 = 080808
$term1 = f447cd
$term2 = ffbac2
$term3 = ffdde9
$term4 = b3a2d5
$term5 = da93cd
$term6 = ffba93
$term7 = ebd2da
$term8 = b09ea4
$term9 = ff77d8
$term10 = ffd2d5
$term11 = fff1f4
$term12 = babfdd
$term13 = ebabda
$term14 = ffd1c0
$term15 = ffffff
$rosewater = feedf4
$flamingo = f6daea
$pink = ffcef6
$mauve = eca9f1
$red = ec98d9
$maroon = e7add6
$peach = fdbbdd
$yellow = ffedf1
$green = ffd8c5
$teal = dedcff
$sky = e8d2ff
$sapphire = deb8ff
$blue = dea9f6
$lavender = ecbcf9
$klink = a374c3
$klinkSelection = a374c3
$kvisited = b362b7
$kvisitedSelection = b362b8
$knegative = d953bd
$knegativeSelection = d953bd
$kneutral = ff7dcc
$kneutralSelection = ff7dcd
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = efddea
$subtext1 = d5c1cf
$subtext0 = 9d8c99
$overlay2 = 1f1b1e
$overlay1 = 1c181b
$overlay0 = 191418
$surface2 = 161015
$surface1 = 120b11
$surface0 = 0a050a
$base = 010002
$mantle = 010002
$crust = 010002
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
