background      = 0xFF010101
base            = 0xFF010101
alternate_base  = 0xFFA3A500
accent          = 0xFFF1F416
accent_secondary = 0xFF469AB3
text            = 0xFFFEFF2B
bright_text     = 0xFFF4F68A
