splash = false

# ── Rebecca / Cyberpunk Edgerunners ───────────
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-kxwp7q.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-6djxy7.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-d6xx9o.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-p933r3.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-exzrmw.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-exzzdo.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-qz99wr.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-weoopx.jpg
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-x655vl.jpg

# ── Cyberpunk 2077 ────────────────────────────
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-kxm6p6.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-2yr3qm.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-qz1q37.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-x6vg7o.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-6okd5l.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-6dv7kw.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-wql2mx.png
preload = /home/kalashnikxv/Pictures/wallpapers/wallhaven-zyvm1j.png

# ── Wallpaper attivo (cambia il percorso a piacere) ──
wallpaper = HDMI-A-1,/home/kalashnikxv/Pictures/wallpapers/wallhaven-kxwp7q.jpg
wallpaper = DP-1,/home/kalashnikxv/Pictures/wallpapers/wallhaven-kxwp7q.jpg
