general {}

listener {
    timeout = 600                               # 10 min: spegni schermi (DPMS off)
    on-timeout = hyprctl dispatch dpms off      # schermo spento, niente lock/suspend
    on-resume  = hyprctl dispatch dpms on       # schermo acceso al primo input
}
