background      = 0xFF050409
base            = 0xFF06050B
alternate_base  = 0xFFC8731D
accent          = 0xFFF99A43
accent_secondary = 0xFFCA2680
text            = 0xFFFFC368
bright_text     = 0xFFF7D3A6
